### ISSUE TITLE
Remove install of not existing directories

### ISSUE THREAD

**Issue by alvarolp02** [ARUSfs/DRIVERLESS2#3]
https://github.com/ARUSfs/DRIVERLESS2/blob/0b7b2482ac61d323a77aa3acde502dbe637e87ba/src/path_planning/CMakeLists.txt#L49-L50

Please remove this two lines in CMakeLists.txt since this folder doesn't exist so colcon doesn't build.

**Comment by igsais** [comment]
Solved in commit [5435a33](https://github.com/ARUSfs/DRIVERLESS2/commit/5435a3355986b831a908875098a33bee8fd66c93).
