### ISSUE TITLE
Don't use custom message as data type

### ISSUE THREAD

**Issue by alvarolp02** [ARUSfs/DRIVERLESS2#46]
https://github.com/ARUSfs/DRIVERLESS2/blob/0358be7855997da34b19ff0fd63458087874f154/src/controller/include/controller/pure_pursuit.h#L16

Custom msgs are only intended for ROS communication, we should never use them as a random data type.
Also, headers like pure_pursuit must be as general as possible, so we cannot use our custom data types like this.
Use two std::vector<double> x_path, y_path instead of common_msgs::msg::PointXY.

Change the data types where necessary at pure_pursuit.h, controller_node.cpp and controller_node.hpp

**Comment by francisrojass** [comment]
I created a Point structure that contains x and y, and I made a header file so I can reference it from controller_node.cpp and pure_pursuit.h. The definitions it includes at the beginning and end, such as #ifndef and #endif, prevent the compiler from compiling it twice when it’s called from two different nodes. I tried removing them, and it gives an error saying the Point structure is compiled twice.
