### ISSUE TITLE
Controller scripts naming

### ISSUE THREAD

**Issue by alvarolp02** [ARUSfs/DRIVERLESS2#48]
Change controller.cpp to controller_node.cpp and controller.hpp to controller_node.hpp

https://github.com/ARUSfs/DRIVERLESS2/blob/0358be7855997da34b19ff0fd63458087874f154/src/controller/CMakeLists.txt#L20
https://github.com/ARUSfs/DRIVERLESS2/blob/0358be7855997da34b19ff0fd63458087874f154/src/controller/CMakeLists.txt#L23
https://github.com/ARUSfs/DRIVERLESS2/blob/0358be7855997da34b19ff0fd63458087874f154/src/controller/CMakeLists.txt#L31
https://github.com/ARUSfs/DRIVERLESS2/blob/0358be7855997da34b19ff0fd63458087874f154/src/controller/launch/controller_launch.py#L16
Also change the executable name from controller to controller_exec to follow the same formats as the rest of the code.

**Comment by francisrojass** [comment]
already
