### ISSUE TITLE
Don't subscribe to arussim

### ISSUE THREAD

**Issue by alvarolp02** [ARUSfs/DRIVERLESS2#49]
https://github.com/ARUSfs/DRIVERLESS2/blob/0358be7855997da34b19ff0fd63458087874f154/src/controller/src/controller.cpp#L29

Subscribe to /car_state/state instead of arussim. Make the necessary changes at hpp and callback

Also remove all dependencies to arussim at hpp, CMakeLists and package.xml

**Comment by francisrojass** [comment]
already

**Comment by alvarolp02** [comment]
Remove arussim dependencies at package.xml and CMakeLists.txt

**Comment by alvarolp02** [comment]
And controller_node.hpp
