### ISSUE TITLE
CAN interface - colcon buildn't !!!

### ISSUE THREAD

**Issue by alvarolp02** [ARUSfs/DRIVERLESS2#55]
https://github.com/ARUSfs/DRIVERLESS2/blob/bcf92f41b6ae3755cdf46f3164b105c82611805f/src/interfaces/can_interface/CMakeLists.txt#L25-L26

The config folder doesn't exist yet, so colcon throws an error:
file INSTALL cannot find
"/home/alvaro/workspaces/ros2_ws/src/DRIVERLESS2/src/perception/config": No
such file or directory.

Please remove these lines until config file is created and always check colcon build before pushing

**Comment by GalisteoAlvaro** [comment]
Lines already remove and push to the branch.
