### ISSUE TITLE
CAN interface - config doesn't exist

### ISSUE THREAD

**Issue by alvarolp02** [ARUSfs/DRIVERLESS2#56]
https://github.com/ARUSfs/DRIVERLESS2/blob/bcf92f41b6ae3755cdf46f3164b105c82611805f/src/interfaces/can_interface/launch/can_interface_launch.py#L11-L12

The config file doesn't exist yet, remove these two lines

**Comment by GalisteoAlvaro** [comment]
Lines already remove from the file and another from "generate_launch_description()" where importing in the Node the config_file define in those lines.
