### ISSUE TITLE
Incorrect scalar division

### ISSUE THREAD

**Issue by javiuv** [ARUSfs/DRIVERLESS2#81]
https://github.com/ARUSfs/DRIVERLESS2/blob/5bdb16499084bdcd76c54983aa9120f40ac2fbcf/src/controller/include/controller/speed_control.hpp#L39-L44

The feedforward term shouldn't be affected by the division "/(230 * 0.2)", it's only needed by PID.
This division is inherited from an old control law used in last year's system, we actually should stop using it and recalculate correct control gains.

**Comment by francisrojass** [comment]
Okay, I have deleted the scalar division and its working correctly. I don't know, if we want to do something different with that or simply deleting
